//LeetCode
//You are given two strings s and t.

//String t is generated by random shuffling string s and then add one more letter at a random position.

//Return the letter that was added to t.

//Example 1:

//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.

//CODE:

class Solution {
public:
    char findTheDifference(string s, string t) {
        sort(s.begin(), s.end());
        sort(t.begin(), t.end());

        int i = 0, j = 0;
        while (j < t.length()) {
            if (s[i] == t[j]) {
                i++;
                j++;
            }
            else
                break;
        }
         return t[j];
    }
};
